name: Build & Publish

on: push

env:
  PKG_NAME: altserver-manager
  DOCKER_USERNAME: steilerdev

# Required secrets:
# DOCKER_PWD            DockerHub password

jobs:
  publish-dockerhub:
    name: Build & Publish project to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup/metadata
      id: npm-metadata
      uses: ./.github/actions/npm-metadata
      with:
        package: ./package.json
    - name: setup/buildx
      uses: docker/setup-buildx-action@v3
    - name: setup/dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    - name: action/push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/arm/v8,linux/arm64
        tags: |
          ${{env.DOCKER_USERNAME}}/${{env.PKG_NAME}}:${{ github.ref == 'refs/heads/main' && 'latest' || 'beta'}}
          ${{env.DOCKER_USERNAME}}/${{env.PKG_NAME}}:${{ steps.npm-metadata.outputs.version }}${{ github.ref == 'refs/heads/main' && '' || '-beta'}}
    - name: push/readme
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}
        repository: ${{env.DOCKER_USERNAME}}/${{env.PKG_NAME}}
        readme-filepath: ./README.md
        short-description: ${{ github.event.repository.description }}