name: Build & Publish

on: push

env:
  PKG_NAME: altserver-manager
  DOCKER_USERNAME: steilerdev

# Required secrets:
# DOCKER_PWD            DockerHub password

jobs:
  publish-dockerhub:
    name: Publish Project to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: npm-metadata
      uses: ./.github/actions/npm-metadata
    - name: setup/buildx
      uses: docker/setup-buildx-action@v2
    - name: setup/dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}
    - name: push/beta
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm,linux/arm64
        tags: 
          - ${{env.DOCKER_USERNAME}}/${{env.PKG_NAME}}:beta
          - ${{env.DOCKER_USERNAME}}/${{env.PKG_NAME}}:${{ steps.npm-metadata.outputs.version }}-beta
    - name: push/latest
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/arm/v8,linux/arm64
        tags: 
          - ${{env.DOCKER_USERNAME}}/${{env.PKG_NAME}}:latest
          - ${{env.DOCKER_USERNAME}}/${{env.PKG_NAME}}:${{ steps.npm-metadata.outputs.version }}
    - name: push/readme
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PWD }}
        repository: ${{env.DOCKER_USERNAME}}/${{env.PKG_NAME}}
        readme-filepath: ./README.md
        short-description: ${{ github.event.repository.description }}v